const exercises = require("./exercises/index.js")

// const res = exercises.getLongestNonRepeatedString("asd")
// const res = exercises.countOccurrences("aabbcb")
// const res = exercises.getLongestRepeatedString("aabbcbaaaddasd")
// const res = exercises.reverseString("Hello")
// const res = exercises.palindromeCheck("radar")
// const res = exercises.anagramCheck("listen", "silent")
// const res = exercises.longestWord("This is a simple test sentence.")
// const res = exercises.countVowels("JavaScript")
// const res = exercises.capitalizeWords("capitalize the first letter")
// const res = exercises.stringCompression("wwwssdwwfccr")
// const res = exercises.countSubstrings("abababab", "ab")
// const res = exercises.stringRotation("waterbottle", "erbottlewat")
const res = exercises.removeDuplicates("programming")

console.log("res=>", res)
