const exercises = require('./exercises/index.js')

// const res = exercises.getLongestNonRepeatedString("asd")
// const res = exercises.countOccurrences("aabbcb")
// const res = exercises.getLongestRepeatedString("aabbcbaaaddasd")
// const res = exercises.reverseString("Hello")
// const res = exercises.palindromeCheck("radar")
// const res = exercises.anagramCheck("listen", "silent")
// const res = exercises.longestWord("This is a simple test sentence.")
// const res = exercises.countVowels("JavaScript")
// const res = exercises.capitalizeWords("capitalize the first letter")
// const res = exercises.stringCompression("wwwssdwwfccr")
// const res = exercises.countSubstrings("abababab", "ab")
// const res = exercises.stringRotation("waterbottle", "erbottlewat")
// const res = exercises.removeDuplicates("programming")
/** ARRAY EXERCISES */

// const res = exercises.sumOfElements([1, 2, 3, 4, 5])
// const res = exercises.removeDuplicatedElements([1, 2, 2, 3, 4, 4, 5])
// const res = exercises.arrayReversal([1, 2, 3, 4, 5])
// const res = exercises.intersectionOfTwoArrays([1, 2, 3, 4], [3, 4, 5, 6])
// const res = exercises.countArrayOccurrences([1, 2, 1, 3, 4, 2, 5, 1])
const res = exercises.moveZerosToEnd([0, 2, 0, 4, 6, 0, 8])

console.log('res=>', res)
